name: TrueEssentials
version: '1.0.4'
main: me.nebu.trueEssentials.TrueEssentials
api-version: '1.19'
softdepend:
  - PlaceholderAPI
loadafter:
  - PlaceholderAPI
author: Nebula
commands:
  trueessentials:
    aliases: [te, truee]
    description: The TrueEssentials command.
    usage: /<command> <text>
  inventorysee:
    description: View another player's inventory.
    aliases: [invsee, inv]
    usage: /<command> <player>
  enderchest:
    description: Open your ender chest or another player's ender chest.
    aliases: ec
    usage: /<command> [<player>]
  flight:
    description: Allow you or another player to fly.
    aliases: fly
    usage: /<command> [<player>]
  kickall:
    description: Kick all online players from the server, except the ones exempt.
    usage: /<command>
  ping:
    description: View your ping or another player's ping.
    usage: /<command> [<player>]
  sudo:
    description: Make another player run the specified command.
    usage: /<command> <player> <sudo command>
  gamemode:
    description: Change your game mode or another player's game mode.
    usage: /<command> <gamemode> [<player>]
  gmc:
    description: Shortcut to the game mode creative command.
    usage: /<command> [<player>]
  gms:
    description: Shortcut to the game mode survival command.
    usage: /<command> [<player>]
  gma:
    description: Shortcut to the game mode adventure command.
    usage: /<command> [<player>]
  gmsp:
    description: Shortcut to the game mode spectator command.
    usage: /<command> [<player>]
  trash:
    aliases: disposal
    description: Opens a disposal menu
    usage: /<command>
  tpask:
    aliases: tpa
    description: Request to teleport to another player
    usage: /<command> <player>
  tpaccept:
    description: Accept the teleportation request of another player
    usage: /<command>
  clearchat:
    aliases: cc
    description: Clears the chat of all players, except the ones exempt.
    usage: /<command>
  spawn:
    description: Teleport you to the spawn
    usage: /<command>
  setspawn:
    description: Sets the spawn location
    usage: /<command>
  homes:
    description: View all your homes
    usage: /<command>
  sethome:
    description: Create a new home
    usage: /<command> <name>
  delhome:
    description: Delete a home
    usage: /<command> <name>
  home:
    description: Teleport to one of your homes
    usage: /<command> <name>
  ban:
    description: Ban a player from your server
    usage: /<command> <player> <reason>
  warn:
    description: Warn a player
    usage: /<command> <player> <reason>
  modlogs:
    description: View the logs of a player
    usage: /<command> <player>
  #lore:
  #  description: Change the lore of your tool
  #  usage: /<command> <text> [<text>]